version: '3.9'

services: 
  mysqldb:
    image: mysql:5.6.51
    container_name: attendancedb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: attendancedb
    ports:
      - 3307:3306
    volumes: 
      - mysql-data:/var/lib/mysql

volumes: 
  mysql-data: